### PR TITLE
Upgrades phpmailer

### PR DESCRIPTION
**Pull request by margori**

### CODE REVIEW

**Comment by margori** [comment]
This change was suggested for dependabot due to security issues on PhpMailer 5.

**Comment by margori** [comment]
This PR is approved but I don't have privilege to merge. Is it planned for later release?

**Comment by Jamesking56** [comment]
I'll release a patch version for this now

**Comment by Jamesking56** [comment]
This doesn't change anything end-user wise so I don't think it needs a patch release

**Pull request merged**
