### PR TITLE
See in nth email

### PR DESCRIPTION
**Pull request by clinoge**

### CODE REVIEW

**Comment by clinoge** [comment]
https://travis-ci.org/captbaritone/codeception-mailcatcher-module/jobs/169962275

**Comment by captbaritone** [comment]
This looks like a nice improvement, and the refactor looks promising too. Any hope of getting tests and documentation for the new methods?

I should have time by this weekend for a proper review.

Thanks for your work on this!

**Comment by clinoge** [comment]
No problem, yes, I'll be writing the tests shortly. I was in a need for 
these methods and rushed to write them so (shame on me) didn't write
any test ahead.

As soon as I get some free time (a day or two) I'll write them ;).

**Comment by fmasa** [comment]
@clinoge Are you still working on this? Would you like some help?

**Comment by Jamesking56** [comment]
This PR is very old and conflicted. Closing due to no response or commit in over 12 months.

**Pull request closed without merging**
