### PR TITLE
Allow PHP8.1 & Codeception5.0

### PR DESCRIPTION
**Pull request by piotrknapik**
Works for me!

### CODE REVIEW

**Review by Jamesking56 — CHANGES_REQUESTED** [review]
Test failures

**Comment by Jamesking56** [comment]
@zyab1ik Please see the issue we have in trying to make this project support both v4 and v5: https://github.com/captbaritone/codeception-mailcatcher-module/issues/105

**Comment by Jamesking56** [comment]
@piotrknapik Please see the issue we have in trying to make this project support both v4 and v5: https://github.com/captbaritone/codeception-mailcatcher-module/issues/105

**Comment by michaelarnauts** [comment]
@Jamesking56 As indicated in https://github.com/captbaritone/codeception-mailcatcher-module/issues/105#issuecomment-1406678596, I also don't think this module should be compatible with all codeception versions that have ever existed. I would suggest to create a new major release that drops support for old versions.

As a workaround, I have added this to my composer.json so it picks up the fork of @piotrknapik.

```
{
    ...
    "require": {
         ...
        "captbaritone/mailcatcher-codeception-module": "dev-master as 2.4.1"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/piotrknapik/codeception-mailcatcher-module.git"
        }
    ],
```

**Comment by michaelarnauts** [comment]
@Jamesking56 i noticed you made a recent release, but this isn't fixed. 

Aren't you okay with this change?

**Comment by Jamesking56** [comment]
Codeception v5 is now supported in [v3.0.0](https://github.com/captbaritone/codeception-mailcatcher-module/releases/tag/3.0.0)

**Pull request closed without merging**
