### PR TITLE
Rename `lastMessageFrom` to `lastMessageTo`

### LINKED ISSUE #51: public function lastMessageFrom should be lastMessageTo
The function looks for the address provided in the recipients of each message ... so I suspect the method name is a bit misleading ... perhaps.

### PR DESCRIPTION
**Pull request by Jamesking56**
Fixes #51 

Deprecate `lastMessageFrom` usage with recipient emails

### CODE REVIEW

**Comment by Patabugen** [comment]
Thanks for this PR! That was giving me issues and I've pulled your PR into my own fork.

One little bug - the error message in the fixed lastMessageFrom if no messages are found still says "No messages sent **to**"

**Comment by Jamesking56** [comment]
@Patabugen Thanks for that I'll do a quick commit to fix it :+1:

**Comment by Jamesking56** [comment]
@Patabugen Can I get a review from you to see if this is correct before I merge? Cheers.

**Comment by Jamesking56** [comment]
@Patabugen any update on this one?

**Comment by Patabugen** [comment]
Sorry. I haven't had a chance to review your code. I fixed this in my fork (but it appears I forgot to send a PR - which I've sent now if you want it). I'm super busy at the moment but will try and look through your commits in the next week or two, feel free to not wait for me!

**Comment by Jamesking56** [comment]
Cheers for getting back to me @Patabugen :+1:

**Pull request closed without merging**
