### PR TITLE
Fix #22 Grab all urls from body

### LINKED ISSUE #22: url attribute on messages?
Hey, I've been using this module for a bit and really like it

I have a thought (and a commit) in regards to a user need that came up in other github issues, which is that of exploring/parsing the HTML of the email while testing.

in the issue threads, the headache of parsing html accurately is mentioned as a reason why there hasn't much movement on this.

Why not include the email's HTML preview URL on mailcatcher (for example, http://localhost:1080/messages/1.html) in the message data? Then the tester can simply use a line of code like `$tester->amOnPage($msg['url'])` to load the emails' HTML into the test browser. From there the full assortment of assertions and helper functions can be brought to bear on the email's content.

here's a commit that illustrates the idea:

https://github.com/agouticreative/codeception-mailcatcher-module/commit/075e0586e45a973b930922782d6fa75463eebc7f

What do you think? Apologies if this is in the code somewhere already and I stared through it, or if there is a fatal flaw to the idea...

### PR DESCRIPTION
**Pull request by margori**
This is my fix to ticket #10 and #22.

Your feedback will be very welcome. Thanks.

### CODE REVIEW

**Comment by margori** [comment]
It's a good idea. I'll try it soon.

**Comment by margori** [comment]
Ready. Is this solution better?

**Comment by margori** [comment]
BUMP. Need review for this PR. Thanks.

**Comment by dzoeteman** [comment]
@margori @captbaritone Apologies for the late response, I have been quite busy the last few months. I'll take a look at the PR in the next week or so!

**Comment by dzoeteman** [comment]
Thanks for your changes! I've merged the PR.

**Comment by margori** [comment]
Thanks!

**Pull request merged**
