### PR TITLE
Add to new methods to access all parts of email messages directly

### PR DESCRIPTION
**Pull request by paulsheldrake**

### CODE REVIEW

**Comment by paulsheldrake** [comment]
The CI is failing because of an issue installing the mailcatcher gem

**Comment by captbaritone** [comment]
Yeah, the test failures are on my end. I think it would be better to just make the protected methods public, rather than wrapping them in a public method when the signature is identical.

**Comment by paulsheldrake** [comment]
@captbaritone Thanks for the feedback, that's been updated

**Comment by captbaritone** [comment]
Tagged this as 1.2.0

**Comment by paulsheldrake** [comment]
Thank you

**Pull request merged**
